name: Build/release

on:
    push:
        branches:
            - '*'

jobs:
    build:
        runs-on: macos-latest
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        strategy:
            matrix:
                platform: [win, mac, linux]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: 'yarn'
            - run: yarn@3.1.1 install
            - run: yarn run make-${{ matrix.platform }}-publish
