name: Build/release
on:
    push:
        branches:
            - '*'

jobs:
    build:
        runs-on: macos-latest
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_TOKEN: ${{ github.token }}

        strategy:
            matrix:
                platform: [win]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: 'yarn'
            - run: yarn install
            - run: yarn run make-${{ matrix.platform }}-publish
            - name: version
              run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
              id: version
            - name: release
              uses: actions/create-release@v1
              id: create_release
              with:
                draft: false
                prerelease: false
                release_name: ${{ steps.version.outputs.version }}
                tag_name: ${{ github.ref }}
                #body_path: CHANGELOG.md
            - name: Upload Exe
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./dist/Chobots^ Client^ Setup^ 1.0.0.exe
                  asset_name: Chobots.exe
                  asset_content_type: application/exe
