name: Build/release
on:
    push:
        branches:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        strategy:
            matrix:
                platform: [win, mac, linux]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - run: npm i -g electron-builder
            - run: sudo npm run make-${{ matrix.platform }}
